### ISSUE TITLE
Hover-over Effects Stick When Pointer Scrolls Off Image

### ISSUE THREAD

**Issue by TrueAegis** [nanostudio-org/nanogallery2#281]
**Describe the bug**
If the pointer hovers off of an image in a gallery while scrolling the hover-on effect remains until hovered over again. Seems like the hover-off event isn't firing when scrolling. 

**To Reproduce**
1. Go to a gallery with hover effects
2. Hover over an image
3. Scroll while removing the pointer from over the image
4. The hover effect should remain

**Expected behavior**
When the pointer is no longer hovering over the image, the image should return to how it was before being hovered over.
  
**CODEPEN**
This can be reproduced via the builder by adding hover effects, test the effect, but scrolling before moving the pointer off of the image.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 84.0.4147.105

**Comment by Kris-B** [comment]
@TrueAegis thanks for your detailed description.
Issue should be fixed in the beta of v3.1.0, available in the `dist` folder of the master-branch (use JS and CSS files from there).
Can you please test it ?

**Comment by TrueAegis** [comment]
@Kris-B 
Sorry for the delay. Yes, I can. I will get back to you when the results.

**Comment by TrueAegis** [comment]
@Kris-B sorry for not getting back earlier than this. 

This update fixes the issue to some degree. I no longer have to hover over an image again to "unstick" the hover-effect. The behavior still persists if I scroll the pointer off an image and don't move the pointer. Moving the pointer does clear out the hover-effect that was stuck.

**Comment by Kris-B** [comment]
Fixed in release v3.0.5
