### ISSUE TITLE
nanoGallery is not a function

### ISSUE THREAD

**Issue by Raf-sns** [nanostudio-org/nanogallery2#310]
try all possibilities ...
```
<head>
<!-- jQuery -->
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js"></script>

  <!-- nanogallery2 -->
  <link  href="https://cdn.jsdelivr.net/npm/nanogallery2@3/dist/css/nanogallery2.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/nanogallery2@3/dist/jquery.nanogallery2.min.js"></script>
</head>
```

```
<h1>Projets</h1>

  <div id="my_nanogallery2" data-nanogallery2></div>

  <script type="text/javascript">
  
  $(function(){

      var ITEMS = [];

      $.o.projects.forEach((item, i) => {

        ITEMS.push({src: item.img_prez_name,
          srct: item.img_prez_name,
          title: item.title });

      });

      // console.log(ITEMS); // OK !


      $("#my_nanogallery2").nanoGallery({
        // ### gallery settings ###
        itemsBaseURL : "https://ima.sns.pm/img/Projects/",
        thumbnailWidth : "auto",
        thumbnailHeight : "400",
        thumbnailBorderVertical : 0,
        thumbnailBorderHorizontal : 0,
        colorScheme : {
          thumbnail : {
            background : "rgba(255,255,255,1)"
          }
        },
        thumbnailLabel : {
          position : "overImageOnBottom",
          titleMultiLine : true
        },
        allowHTMLinData : true,
        thumbnailHoverEffect2 : "toolsAppear|labelSlideUp|imageScaleIn80",
        thumbnailAlignment : "center",
        thumbnailGutterWidth : 10,
        thumbnailGutterHeight : 10,
        displayBreadcrumb : false,
        breadcrumbAutoHideTopLevel : false,
        breadcrumbOnlyCurrentLevel : false,
        thumbnailOpenImage : true,

        // ### gallery content ###
        items: ITEMS
      });

  });
  // end jQuery
  </script>
```

Always return Uncaught TypeError: $(...).nanoGallery is not a function ...
4 hours of test ...
Disapointed ...

**Comment by Raf-sns** [comment]
Exemple code was buged ...
here -> https://nanogallery2.nanostudio.org/datasource.html#ngy2_define_javascript
-> javascript
buged code : 

```
<div id="my_nanogallery2" data-nanogallery2></div>

<script>
  $(document).ready(function () {
    $("#my_nanogallery2").nanoGallery({
      items: [
        {
          src:          'image_01.jpg',    // image url
          srct:         'image_01ts.jpg',  // thumbnail url
          title:        'Title Image1',    // media title
          description:  'Description1'     // media description
        },
        { src: 'image_02.jpg', srct: 'image_02t.jpg',  title: 'Title Image2' },
        { src: 'image_03.jpg', srct: 'image_03ts.jpg', title: 'Title Image3' }
      ]
    )}; // BAD CLOSE !
  )}; // BAD CLOSE !
</script>
```

**Comment by Raf-sns** [comment]
Sloved ! - WARNING ! the documentation is completly bugged
it's 
$(...)nanogallery2({ ... }); AND NOT $(...).nanoGallery({ ... });
5 fucking hours ! 
Thanks to un-bug the documentation

**Comment by Kris-B** [comment]
Sorry for all the typos and thanks for reporting.
Fixed.

**Comment by JanVeb** [comment]
<script>
      $(document).ready(function() {
        $("#nanogallery2").nanogallery2({
          // Your NanoGallery2 configuration options go here
        });
      });
    </script>
    
    Still had issue figuring out, upper code is right, bottom code is wrong, from upper solution had issue figuring out where in code nanoGallery was written wrong. In documentation there is still wrong code
    
    
       <script>
   console.log('jQuery', !!window.jQuery);


      $(document).ready(function() {
        $("#nanogallery2").nanoGallery({
          // Your NanoGallery2 configuration options go here
        });
      });
    </script>
